before_install:
  - sudo apt-get install -y ninja-build python3-pytest python3-pytest-xdist
language: c
os: linux
dist: bionic
compiler:
  - gcc
  - clang
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
script: ./scripts/travistest.sh
